name: Windows

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    paths:
      - '**/CMakeLists.txt'
      - '**.cpp'
      - '**.h'
      - 'test/**'
      

jobs:
  build-windows:
    name: Build and run tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1.5.0

    - name: Configure CMake
      env:
          CC: cl.exe
          CXX: cl.exe
      run: |
        mkdir -p build
        cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DANGEL_TEST=ON
    - name: Build tests
      working-directory: build
      run: nmake run_tests

    - name: Run test
      run: |
        .\build\test\run_tests.exe